package ru.akvine.wild.bot.enums;

public enum ClientState {
    MAIN_MENU,
    TESTS_MENU,
    INSTRUCTIONS_MENU,
    SUBSCRIBE_MENU,
    GENERATE_REPORT_MENU,
    LIST_STARTED_TESTS_MENU,
    FINISH_GENERATION_REPORT_MENU,
    FILL_ADVERTISING_ACCOUNT_MENU,
    DETAIL_TEST_INFO_MENU,

    CHOOSE_TYPE_MENU,
    CHOOSE_CATEGORY_MENU,
    UPLOAD_PHOTO_MENU,
    IS_CHANGE_PRICE_MENU,
    INPUT_NEW_PRICE_MENU,
    INPUT_NEW_DISCOUNT_MENU,
    ACCEPT_NEW_PRICE_MENU
}
