version: '3.8'
services:
  marketspace-bot:
    image: marketspace-bot
    container_name: marketspace-bot
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8106:8106"
    depends_on:
      - postgres-db
    environment:
      - SERVER_PORT=8106
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db/marketspace-bot

  postgres-db:
    container_name: postgres-db
    image: postgres:14.7-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_ROOT_PASSWORD:
      POSTGRES_DB: marketspace-bot
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./src/main/resources/db/changelog/database-changelog.sql:/docker-entrypoint-initdb.d/database-changelog.sql
    restart: unless-stopped

volumes:
  db-data: