INSERT INTO CLIENT_ENTITY (ID, UUID, CHAT_ID, USERNAME, FIRST_NAME, LAST_NAME, IS_IN_WHITELIST, CREATED_DATE, IS_DELETED) VALUES (-1, 'uuid_1', '2', 'username_1', 'first_name_1', 'last_name_1', true, '2024-01-04', 0);
INSERT INTO CLIENT_ENTITY (ID, UUID, CHAT_ID, USERNAME, FIRST_NAME, LAST_NAME, IS_IN_WHITELIST, CREATED_DATE, IS_DELETED) VALUES (-2, 'uuid_2', '3', 'username_2', 'first_name_2', 'last_name_2', true, '2024-01-04', 0);
INSERT INTO CLIENT_ENTITY (ID, UUID, CHAT_ID, USERNAME, FIRST_NAME, LAST_NAME, IS_IN_WHITELIST, CREATED_DATE, IS_DELETED) VALUES (-3, 'uuid_3', '4', 'username_3', 'first_name_3', 'last_name_3', true, '2024-01-04', 0);
INSERT INTO CLIENT_ENTITY (ID, UUID, CHAT_ID, USERNAME, FIRST_NAME, LAST_NAME, IS_IN_WHITELIST, CREATED_DATE, IS_DELETED) VALUES (-4, 'uuid_4', '5', 'username_4', 'first_name_4', 'last_name_4', true, '2024-01-04', 0);
INSERT INTO CLIENT_ENTITY (ID, UUID, CHAT_ID, USERNAME, FIRST_NAME, LAST_NAME, IS_IN_WHITELIST, CREATED_DATE, IS_DELETED) VALUES (-5, 'uuid_5', '6', 'username_5', 'first_name_5', 'last_name_5', true, '2024-01-04', 0);
INSERT INTO CLIENT_ENTITY (ID, UUID, CHAT_ID, USERNAME, FIRST_NAME, LAST_NAME, IS_IN_WHITELIST, CREATED_DATE, IS_DELETED) VALUES (-6, 'uuid_6', '7', 'username_6', 'first_name_6', 'last_name_6', true, '2024-01-04', 0);
INSERT INTO CLIENT_ENTITY (ID, UUID, CHAT_ID, USERNAME, FIRST_NAME, LAST_NAME, IS_IN_WHITELIST, CREATED_DATE, IS_DELETED) VALUES (-7, 'uuid_7', '8', 'username_7', 'first_name_7', 'last_name_7', true, '2024-01-04', 0);

INSERT INTO SUBSCRIPTION_ENTITY (ID, CLIENT_ID, EXPIRES_AT, IS_NOTIFIED_THAT_EXPIRES, CREATED_DATE) VALUES (-1, -1, '2040-01-01', false, '2024-01-04');
INSERT INTO SUBSCRIPTION_ENTITY (ID, CLIENT_ID, EXPIRES_AT, IS_NOTIFIED_THAT_EXPIRES, CREATED_DATE) VALUES (-2, -2, '2040-01-01', false, '2024-01-04');
INSERT INTO SUBSCRIPTION_ENTITY (ID, CLIENT_ID, EXPIRES_AT, IS_NOTIFIED_THAT_EXPIRES, CREATED_DATE) VALUES (-3, -3, '2040-01-01', false, '2024-01-04');
INSERT INTO SUBSCRIPTION_ENTITY (ID, CLIENT_ID, EXPIRES_AT, IS_NOTIFIED_THAT_EXPIRES, CREATED_DATE) VALUES (-4, -4, '2040-01-01', false, '2024-01-04');
INSERT INTO SUBSCRIPTION_ENTITY (ID, CLIENT_ID, EXPIRES_AT, IS_NOTIFIED_THAT_EXPIRES, CREATED_DATE) VALUES (-5, -5, '2040-01-01', false, '2024-01-04');
INSERT INTO SUBSCRIPTION_ENTITY (ID, CLIENT_ID, EXPIRES_AT, IS_NOTIFIED_THAT_EXPIRES, CREATED_DATE) VALUES (-6, -6, '2040-01-01', false, '2024-01-04');
INSERT INTO SUBSCRIPTION_ENTITY (ID, CLIENT_ID, EXPIRES_AT, IS_NOTIFIED_THAT_EXPIRES, CREATED_DATE) VALUES (-7, -7, '2040-01-01', false, '2024-01-04');

INSERT INTO CARD_TYPE_ENTITY (ID, TYPE, CREATED_DATE) VALUES (-1, 'Мужской', '2024-01-04');
INSERT INTO CARD_TYPE_ENTITY (ID, TYPE, CREATED_DATE) VALUES (-2, 'Женский', '2024-01-04');

INSERT INTO CARD_ENTITY (ID, UUID, EXTERNAL_ID, EXTERNAL_TITLE, CATEGORY_ID, CATEGORY_TITLE, BARCODE, CARD_TYPE_ID, CREATED_DATE, IS_DELETED) VALUES (-1, 'uuid_1', -1, 'external_title_1', 1, 'title_1', 'barcode_1', -1, '2024-01-04', false);
INSERT INTO CARD_ENTITY (ID, UUID, EXTERNAL_ID, EXTERNAL_TITLE, CATEGORY_ID, CATEGORY_TITLE, BARCODE, CARD_TYPE_ID, CREATED_DATE, IS_DELETED) VALUES (-2, 'uuid_2', -2, 'external_title_2', 2, 'Обувь', 'barcode_2', -1, '2024-01-04', false);

INSERT INTO ADVERT_ENTITY (ID, UUID, EXTERNAL_ID, EXTERNAL_TITLE, CHANGE_TIME, STATUS, ORDINAL_STATUS, TYPE, ORDINAL_TYPE, CPM, IS_LOCKED, START_CHECK_DATE_TIME, CARD_ID, CREATED_DATE, IS_DELETED) VALUES (-1, 'uuid_1', -1, 'external_title_1', '2024-01-04 15:00:00', 'PAUSE', 11, 'AUTO', 8, 700, false, '2024-01-04', -1, '2024-01-04', false);
INSERT INTO ADVERT_ENTITY (ID, UUID, EXTERNAL_ID, EXTERNAL_TITLE, CHANGE_TIME, STATUS, ORDINAL_STATUS, TYPE, ORDINAL_TYPE, CPM, IS_LOCKED, START_CHECK_DATE_TIME, CARD_ID, CREATED_DATE, IS_DELETED) VALUES (-2, 'uuid_2', -2, 'external_title_2', '2024-01-04 15:00:00', 'PAUSE', 11, 'AUTO', 8, 700, false, '2024-01-04', -2, '2024-01-04', false);

INSERT INTO ADVERT_STATISTIC_ENTITY (ID, VIEWS, CLICKS, CTR, CPC, SUM, ATBS, ORDERS, CR, SHKS, SUM_PRICE, PHOTO, IS_ACTIVE, ADVERT_ID, CLIENT_ID, CREATED_DATE, IS_DELETED) VALUES (-1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, '938', false, -1, -4, '2024-01-04', false);