package ru.akvine.wild.bot.infrastructure.monitoring;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;

/**
 * {@link Statement} с замером времени выполнения: все {@code execute*} измеряются, остальные
 * методы - чистое делегирование. Для {@link PreparedStatement} см. наследника
 * {@link MonitoringPreparedStatementProxy}.
 */
public class MonitoringStatementProxy implements Statement {
    @FunctionalInterface
    protected interface SqlCall<T> {
        T call() throws SQLException;
    }

    private final Statement targetStatement;
    private final SqlExecutionListener listener;
    private final List<String> batchedSql = new ArrayList<>();

    public MonitoringStatementProxy(Statement targetStatement, SqlExecutionListener listener) {
        this.targetStatement = targetStatement;
        this.listener = listener;
    }

    protected <T> T timed(String sql, SqlCall<T> call) throws SQLException {
        long startedAtNanos = System.nanoTime();
        try {
            return call.call();
        } finally {
            listener.onQueryExecuted(sql, startedAtNanos);
        }
    }

    protected String batchLabel() {
        return "batch " + batchedSql;
    }

    @Override
    public ResultSet executeQuery(String sql) throws SQLException {
        return timed(sql, () -> targetStatement.executeQuery(sql));
    }

    @Override
    public int executeUpdate(String sql) throws SQLException {
        return timed(sql, () -> targetStatement.executeUpdate(sql));
    }

    @Override
    public int executeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
        return timed(sql, () -> targetStatement.executeUpdate(sql, autoGeneratedKeys));
    }

    @Override
    public int executeUpdate(String sql, int[] columnIndexes) throws SQLException {
        return timed(sql, () -> targetStatement.executeUpdate(sql, columnIndexes));
    }

    @Override
    public int executeUpdate(String sql, String[] columnNames) throws SQLException {
        return timed(sql, () -> targetStatement.executeUpdate(sql, columnNames));
    }

    @Override
    public boolean execute(String sql) throws SQLException {
        return timed(sql, () -> targetStatement.execute(sql));
    }

    @Override
    public boolean execute(String sql, int autoGeneratedKeys) throws SQLException {
        return timed(sql, () -> targetStatement.execute(sql, autoGeneratedKeys));
    }

    @Override
    public boolean execute(String sql, int[] columnIndexes) throws SQLException {
        return timed(sql, () -> targetStatement.execute(sql, columnIndexes));
    }

    @Override
    public boolean execute(String sql, String[] columnNames) throws SQLException {
        return timed(sql, () -> targetStatement.execute(sql, columnNames));
    }

    @Override
    public long executeLargeUpdate(String sql) throws SQLException {
        return timed(sql, () -> targetStatement.executeLargeUpdate(sql));
    }

    @Override
    public long executeLargeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
        return timed(sql, () -> targetStatement.executeLargeUpdate(sql, autoGeneratedKeys));
    }

    @Override
    public long executeLargeUpdate(String sql, int[] columnIndexes) throws SQLException {
        return timed(sql, () -> targetStatement.executeLargeUpdate(sql, columnIndexes));
    }

    @Override
    public long executeLargeUpdate(String sql, String[] columnNames) throws SQLException {
        return timed(sql, () -> targetStatement.executeLargeUpdate(sql, columnNames));
    }

    @Override
    public void addBatch(String sql) throws SQLException {
        targetStatement.addBatch(sql);
        batchedSql.add(sql);
    }

    @Override
    public void clearBatch() throws SQLException {
        targetStatement.clearBatch();
        batchedSql.clear();
    }

    @Override
    public int[] executeBatch() throws SQLException {
        try {
            return timed(batchLabel(), targetStatement::executeBatch);
        } finally {
            batchedSql.clear();
        }
    }

    @Override
    public long[] executeLargeBatch() throws SQLException {
        try {
            return timed(batchLabel(), targetStatement::executeLargeBatch);
        } finally {
            batchedSql.clear();
        }
    }

    @Override
    public void close() throws SQLException {
        targetStatement.close();
    }

    @Override
    public int getMaxFieldSize() throws SQLException {
        return targetStatement.getMaxFieldSize();
    }

    @Override
    public void setMaxFieldSize(int max) throws SQLException {
        targetStatement.setMaxFieldSize(max);
    }

    @Override
    public int getMaxRows() throws SQLException {
        return targetStatement.getMaxRows();
    }

    @Override
    public void setMaxRows(int max) throws SQLException {
        targetStatement.setMaxRows(max);
    }

    @Override
    public long getLargeMaxRows() throws SQLException {
        return targetStatement.getLargeMaxRows();
    }

    @Override
    public void setLargeMaxRows(long max) throws SQLException {
        targetStatement.setLargeMaxRows(max);
    }

    @Override
    public void setEscapeProcessing(boolean enable) throws SQLException {
        targetStatement.setEscapeProcessing(enable);
    }

    @Override
    public int getQueryTimeout() throws SQLException {
        return targetStatement.getQueryTimeout();
    }

    @Override
    public void setQueryTimeout(int seconds) throws SQLException {
        targetStatement.setQueryTimeout(seconds);
    }

    @Override
    public void cancel() throws SQLException {
        targetStatement.cancel();
    }

    @Override
    public SQLWarning getWarnings() throws SQLException {
        return targetStatement.getWarnings();
    }

    @Override
    public void clearWarnings() throws SQLException {
        targetStatement.clearWarnings();
    }

    @Override
    public void setCursorName(String name) throws SQLException {
        targetStatement.setCursorName(name);
    }

    @Override
    public ResultSet getResultSet() throws SQLException {
        return targetStatement.getResultSet();
    }

    @Override
    public int getUpdateCount() throws SQLException {
        return targetStatement.getUpdateCount();
    }

    @Override
    public long getLargeUpdateCount() throws SQLException {
        return targetStatement.getLargeUpdateCount();
    }

    @Override
    public boolean getMoreResults() throws SQLException {
        return targetStatement.getMoreResults();
    }

    @Override
    public boolean getMoreResults(int current) throws SQLException {
        return targetStatement.getMoreResults(current);
    }

    @Override
    public void setFetchDirection(int direction) throws SQLException {
        targetStatement.setFetchDirection(direction);
    }

    @Override
    public int getFetchDirection() throws SQLException {
        return targetStatement.getFetchDirection();
    }

    @Override
    public void setFetchSize(int rows) throws SQLException {
        targetStatement.setFetchSize(rows);
    }

    @Override
    public int getFetchSize() throws SQLException {
        return targetStatement.getFetchSize();
    }

    @Override
    public int getResultSetConcurrency() throws SQLException {
        return targetStatement.getResultSetConcurrency();
    }

    @Override
    public int getResultSetType() throws SQLException {
        return targetStatement.getResultSetType();
    }

    @Override
    public Connection getConnection() throws SQLException {
        return targetStatement.getConnection();
    }

    @Override
    public ResultSet getGeneratedKeys() throws SQLException {
        return targetStatement.getGeneratedKeys();
    }

    @Override
    public int getResultSetHoldability() throws SQLException {
        return targetStatement.getResultSetHoldability();
    }

    @Override
    public boolean isClosed() throws SQLException {
        return targetStatement.isClosed();
    }

    @Override
    public void setPoolable(boolean poolable) throws SQLException {
        targetStatement.setPoolable(poolable);
    }

    @Override
    public boolean isPoolable() throws SQLException {
        return targetStatement.isPoolable();
    }

    @Override
    public void closeOnCompletion() throws SQLException {
        targetStatement.closeOnCompletion();
    }

    @Override
    public boolean isCloseOnCompletion() throws SQLException {
        return targetStatement.isCloseOnCompletion();
    }

    @Override
    public <T> T unwrap(Class<T> iface) throws SQLException {
        return targetStatement.unwrap(iface);
    }

    @Override
    public boolean isWrapperFor(Class<?> iface) throws SQLException {
        return targetStatement.isWrapperFor(iface);
    }
}
