package ru.akvine.marketspace.bot.enums;

public enum ClientState {
    CHOOSE_CATEGORY_STATE,
    UPLOAD_NEW_CARD_PHOTO_STATE,
    IS_NEED_INPUT_NEW_CARD_PRICE_STATE,
    INPUT_NEW_CARD_PRICE_STATE,
    INPUT_NEW_CARD_DISCOUNT_STATE,
    ACCEPT_NEW_PRICE_AND_DISCOUNT_STATE,
    INPUT_STATISTIC_ID;
}
